# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\about.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_About(object):
    def setupUi(self, About):
        About.setObjectName("About")
        About.resize(535, 543)
        About.setAutoFillBackground(False)
        About.setSizeGripEnabled(False)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(About)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_27 = QtWidgets.QLabel(About)
        self.label_27.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_27.setObjectName("label_27")
        self.verticalLayout.addWidget(self.label_27)
        self.label_24 = QtWidgets.QLabel(About)
        self.label_24.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.label_26 = QtWidgets.QLabel(About)
        self.label_26.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_26.setObjectName("label_26")
        self.verticalLayout.addWidget(self.label_26)
        self.label_25 = QtWidgets.QLabel(About)
        self.label_25.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_25.setObjectName("label_25")
        self.verticalLayout.addWidget(self.label_25)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(18, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame1 = QtWidgets.QFrame(About)
        self.frame1.setMinimumSize(QtCore.QSize(80, 80))
        self.frame1.setMaximumSize(QtCore.QSize(80, 80))
        self.frame1.setStyleSheet("#frame1 {\n"
"    image: url(:/logo/kurokesu3.png);\n"
"    image: url(:/logo/kurokesu3.png);\n"
"    /*background-image: url(:/logo/kurokesu3.png) no-repeat center center fixed;*/\n"
"    border-image: url(:/logo/kurokesu3.png) 0 0 0 0 stretch stretch;\n"
"    border-width: 0px;\n"
"}")
        self.frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame1.setObjectName("frame1")
        self.verticalLayout_2.addWidget(self.frame1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 18, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.frame2 = QtWidgets.QFrame(About)
        self.frame2.setMinimumSize(QtCore.QSize(500, 345))
        self.frame2.setMaximumSize(QtCore.QSize(500, 345))
        self.frame2.setStyleSheet("#frame2 {\n"
"    border-image: url(:/logo/rsb1_5.png) 0 0 0 0 stretch stretch;\n"
"\n"
"}")
        self.frame2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame2.setObjectName("frame2")
        self.horizontalLayout_2.addWidget(self.frame2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.buttonBox = QtWidgets.QDialogButtonBox(About)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_3.addWidget(self.buttonBox)

        self.retranslateUi(About)
        self.buttonBox.accepted.connect(About.accept)
        self.buttonBox.rejected.connect(About.reject)
        QtCore.QMetaObject.connectSlotsByName(About)

    def retranslateUi(self, About):
        _translate = QtCore.QCoreApplication.translate
        About.setWindowTitle(_translate("About", "About"))
        self.label_27.setText(_translate("About", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600;\">Kurokesu rotary stage control software<br/>for 360 product photography</span></p><p align=\"center\"><span style=\" font-weight:600;\"><br/></span></p></body></html>"))
        self.label_24.setText(_translate("About", "<html><head/><body><p><span style=\" font-weight:600;\">RSB1</span> rotary stage documentation <a href=\"https://wiki.kurokesu.com/shelves/motion-actuators\"><span style=\" text-decoration: underline; color:#0000ff;\">https://wiki.kurokesu.com/shelves/motion-actuators</span></a></p></body></html>"))
        self.label_26.setText(_translate("About", "<html><head/><body><p><span style=\" font-weight:600;\">SCE2</span> Controller documentation <a href=\"https://wiki.kurokesu.com/shelves/motion-controllers\"><span style=\" text-decoration: underline; color:#0000ff;\">https://wiki.kurokesu.com/shelves/motion-controllers</span></a></p></body></html>"))
        self.label_25.setText(_translate("About", "<html><head/><body><p>Order <span style=\" font-weight:600;\">RSB1</span> rotary stage <a href=\"https://www.kurokesu.com/shop/motion_systems\"><span style=\" text-decoration: underline; color:#0000ff;\">https://www.kurokesu.com/shop/motion_systems</span></a></p></body></html>"))
import images_rc
