# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\grbl_settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GRBLSettings(object):
    def setupUi(self, GRBLSettings):
        GRBLSettings.setObjectName("GRBLSettings")
        GRBLSettings.resize(467, 790)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(GRBLSettings)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(GRBLSettings)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table_gcode_log = QtWidgets.QTableWidget(self.groupBox_2)
        self.table_gcode_log.setObjectName("table_gcode_log")
        self.table_gcode_log.setColumnCount(3)
        self.table_gcode_log.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_gcode_log.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_gcode_log.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_gcode_log.setHorizontalHeaderItem(2, item)
        self.verticalLayout.addWidget(self.table_gcode_log)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_3.addWidget(self.groupBox_2)

        self.retranslateUi(GRBLSettings)
        QtCore.QMetaObject.connectSlotsByName(GRBLSettings)

    def retranslateUi(self, GRBLSettings):
        _translate = QtCore.QCoreApplication.translate
        GRBLSettings.setWindowTitle(_translate("GRBLSettings", "GRBL Settings"))
        self.groupBox_2.setTitle(_translate("GRBLSettings", "GRBL parameters"))
        item = self.table_gcode_log.horizontalHeaderItem(0)
        item.setText(_translate("GRBLSettings", "Parameter"))
        item = self.table_gcode_log.horizontalHeaderItem(1)
        item.setText(_translate("GRBLSettings", "Value"))
        item = self.table_gcode_log.horizontalHeaderItem(2)
        item.setText(_translate("GRBLSettings", "Comment"))
        self.pushButton.setText(_translate("GRBLSettings", "Read"))
        self.pushButton_2.setText(_translate("GRBLSettings", "Write"))
        self.pushButton_3.setText(_translate("GRBLSettings", "Cancel"))
