# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\presets.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ManualControl(object):
    def setupUi(self, ManualControl):
        ManualControl.setObjectName("ManualControl")
        ManualControl.resize(358, 333)
        self.groupBox_4 = QtWidgets.QGroupBox(ManualControl)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 60, 146, 112))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_25.addWidget(self.label_25)
        self.double_position = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.double_position.setMinimum(-999999.0)
        self.double_position.setMaximum(999999.0)
        self.double_position.setObjectName("double_position")
        self.horizontalLayout_25.addWidget(self.double_position)
        self.verticalLayout.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_27.addWidget(self.label_27)
        self.double_speed = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.double_speed.setMaximum(999999.0)
        self.double_speed.setObjectName("double_speed")
        self.horizontalLayout_27.addWidget(self.double_speed)
        self.verticalLayout.addLayout(self.horizontalLayout_27)
        self.push_manual_go = QtWidgets.QPushButton(self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.push_manual_go.sizePolicy().hasHeightForWidth())
        self.push_manual_go.setSizePolicy(sizePolicy)
        self.push_manual_go.setObjectName("push_manual_go")
        self.verticalLayout.addWidget(self.push_manual_go)

        self.retranslateUi(ManualControl)
        QtCore.QMetaObject.connectSlotsByName(ManualControl)

    def retranslateUi(self, ManualControl):
        _translate = QtCore.QCoreApplication.translate
        ManualControl.setWindowTitle(_translate("ManualControl", "Manual Control"))
        self.groupBox_4.setTitle(_translate("ManualControl", "Preset1"))
        self.label_25.setText(_translate("ManualControl", "Position"))
        self.label_27.setText(_translate("ManualControl", "Speed"))
        self.push_manual_go.setText(_translate("ManualControl", "GO"))
