# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(400, 229)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.check_remember_last_loaded_profile = QtWidgets.QCheckBox(Settings)
        self.check_remember_last_loaded_profile.setEnabled(False)
        self.check_remember_last_loaded_profile.setObjectName("check_remember_last_loaded_profile")
        self.verticalLayout.addWidget(self.check_remember_last_loaded_profile)
        self.check_remember_last_com_port = QtWidgets.QCheckBox(Settings)
        self.check_remember_last_com_port.setEnabled(False)
        self.check_remember_last_com_port.setObjectName("check_remember_last_com_port")
        self.verticalLayout.addWidget(self.check_remember_last_com_port)
        self.check_auto_connect_after_restart = QtWidgets.QCheckBox(Settings)
        self.check_auto_connect_after_restart.setEnabled(False)
        self.check_auto_connect_after_restart.setObjectName("check_auto_connect_after_restart")
        self.verticalLayout.addWidget(self.check_auto_connect_after_restart)
        self.check_beep_when_done = QtWidgets.QCheckBox(Settings)
        self.check_beep_when_done.setEnabled(False)
        self.check_beep_when_done.setObjectName("check_beep_when_done")
        self.verticalLayout.addWidget(self.check_beep_when_done)
        self.check_flash_when_done = QtWidgets.QCheckBox(Settings)
        self.check_flash_when_done.setEnabled(False)
        self.check_flash_when_done.setObjectName("check_flash_when_done")
        self.verticalLayout.addWidget(self.check_flash_when_done)
        self.check_start_compact = QtWidgets.QCheckBox(Settings)
        self.check_start_compact.setEnabled(False)
        self.check_start_compact.setObjectName("check_start_compact")
        self.verticalLayout.addWidget(self.check_start_compact)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 39, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(Settings)
        self.buttonBox.accepted.connect(Settings.accept)
        self.buttonBox.rejected.connect(Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.check_remember_last_loaded_profile.setText(_translate("Settings", "Remember last loaded profile"))
        self.check_remember_last_com_port.setText(_translate("Settings", "Remember last com port"))
        self.check_auto_connect_after_restart.setText(_translate("Settings", "Try to connect automatically after program restart"))
        self.check_beep_when_done.setText(_translate("Settings", "Beep when done"))
        self.check_flash_when_done.setText(_translate("Settings", "Flash color when done"))
        self.check_start_compact.setText(_translate("Settings", "Start with compact view"))
